# Generated by Django 3.2 on 2023-07-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230727_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Ингредиенты в рецептах', 'verbose_name_plural': 'Ингредиент в рецепт'},
        ),
    ]
