# Generated by Django 3.2 on 2023-07-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientrecipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Ингредиент в рецепт', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
    ]
